import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import QueryProvider from "@/components/providers/QueryProvider";

const quickSand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
});

export const metadata: Metadata = {
  title: "First Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(quickSand.variable, ` antialiased`)}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
